export const DUMMY_MARCAS = [
    {
    id: 'm1',
    name: 'Quimica PIMA',
    pagina: 'https://agricompra.com/store/QUIMICA-PIMA/26',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/b9a2b882-6a66-11f0-a712-0242ac180002_large.jpg',
  },
  {
    id: 'm2',
    name: 'Agroinsumos EMSA',
    pagina: 'https://agricompra.com/store/AGROINSUMOS-EMSA,-SA-DE-CV/49',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/d3b08a38-6a66-11f0-b2f0-0242ac180002_large.jpg',
  },
  {
    id: 'm3',
    name: 'Proviapack',
    pagina: 'https://agricompra.com/store/ProviPack-Insumos/62',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/fc1e6c4c-6a66-11f0-afb7-0242ac180002_large.jpg',
  },
  {
    id: 'm4',
    name: 'Bioproductos Agricolas',
    pagina: 'https://agricompra.com/store/Bioproductos-Agricolas/260',   
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/325ad2f0-6a67-11f0-a29a-0242ac180002_large.jpg',
  },
  {
    id: 'm5',
    name: 'LOF',
    pagina: 'https://agricompra.com/store/LOF/27',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/5a658542-6a67-11f0-a181-0242ac180002_large.jpg',
  },
  {
    id: 'm6',
    name: 'North American',
    pagina: 'https://agricompra.com/store/North-American-Greenhouses/445',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/327eee22-6a69-11f0-ad3f-0242ac180002_large.jpg',
  },
]