export const DUMMY_MARCAS = [
    {
    id: 'm1',
    name: 'Quimica PIMA',
    pagina: 'https://agricompra.com/store/QUIMICA-PIMA/26',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/b9a2b882-6a66-11f0-a712-0242ac180002_large.jpg',
  },
  {
    id: 'm2',
    name: 'Agroinsumos EMSA',
    pagina: 'https://agricompra.com/store/AGROINSUMOS-EMSA,-SA-DE-CV/49',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/d3b08a38-6a66-11f0-b2f0-0242ac180002_large.jpg',
  },
  {
    id: 'm3',
    name: 'Proviapack',
    pagina: 'https://agricompra.com/store/ProviPack-Insumos/62',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/fc1e6c4c-6a66-11f0-afb7-0242ac180002_large.jpg',
  },
  {
    id: 'm4',
    name: 'Bioproductos Agricolas',
    pagina: 'https://agricompra.com/store/Bioproductos-Agricolas/260',   
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/325ad2f0-6a67-11f0-a29a-0242ac180002_large.jpg',
  },
  {
    id: 'm5',
    name: 'LOF',
    pagina: 'https://agricompra.com/store/LOF/27',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/5a658542-6a67-11f0-a181-0242ac180002_large.jpg',
  },
  {
    id: 'm6',
    name: 'North American',
    pagina: 'https://agricompra.com/store/North-American-Greenhouses/445',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/327eee22-6a69-11f0-ad3f-0242ac180002_large.jpg',
  },
      {
    id: 'm7',
    name: 'Agrisem',
    pagina: 'https://agricompra.com/store/AGROINSUMOS-Y-SEMILLAS-DE-LA-REGI%C3%93N/147',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/7872b10e-6a67-11f0-a712-0242ac180002_large.jpg',
  },
  {
    id: 'm8',
    name: 'Amigo Safety',
    pagina: 'https://agricompra.com/store/SEGURIDAD-INDUSTRIAL-AMIGO-SA-DE-CV-/814',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/9b35eecc-6a67-11f0-a272-0242ac180002_large.jpg',
  },
  {
    id: 'm9',
    name: 'Comerplasin',
    pagina: 'https://agricompra.com/store/Comerplasin-S-de-RL/55',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/b89857ca-6a67-11f0-adac-0242ac180002_large.jpg',
  },
  {
    id: 'm10',
    name: 'Passa Agroservicios',
    pagina: 'https://agricompra.com/store/PASSA-Agroservicios/78',   
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/d5567d60-6a67-11f0-89bd-0242ac180002_large.jpg',
  },
  {
    id: 'm11',
    name: 'Agrorganicos Nacionales',
    pagina: 'https://agricompra.com/store/AGRORGANICOS-NACIONALES/1377',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/ecab4bd0-6a67-11f0-b912-0242ac180002_large.jpg',
  },
  {
    id: 'm12',
    name: 'Koppert',
    pagina: 'https://agricompra.com/store/Koppert/176',
    avatar: 'https://storage.googleapis.com/agricompra-com-media/attachment_order/06ca0bc8-6a68-11f0-af42-0242ac180002_large.jpg',
  },
]